In [1]:
from tensorflow.keras.datasets import mnist

In [2]:
#load  the dataset
(X_train, y_train),(X_test, y_test)=mnist.load_data()

In [3]:
#let us print the shape of the datasets
print("X_train shape", X_train.shape)
print("y_train shape", y_train.shape)
print("X_test shape", X_test.shape)
print("X_test shape", y_test.shape)

X_train shape (60000, 28, 28)
y_train shape (60000,)
X_test shape (10000, 28, 28)
X_test shape (10000,)


###### Steps to build an Image Classification Model using CNN

In [4]:
# 1. Flatten the input image dimension to 1D (width pixels X height)
# 2. Normalise the image pixel values (divided by 255)
# 3. One hot encode the categorical column
# 4. Build a model architecture (Sequential) with dense Layers(fully Connected layers)
# 5. Train the model and make the predictiond

In [5]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout, Conv2D, MaxPooling2D
from tensorflow.keras.utils import to_categorical
#The np_utils is used for categorical encodings, such as converting class vectors to binary class matrices.

In [6]:
from keras.utils import to_categorical
y_class = [2, 5, 7, 1]
y_binary = to_categorical(y_class)
print(y_binary)

[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0.]]


In [7]:
#flattering the image from the 28x28 pixels to 1D 787 pixels.
X_train=X_train.reshape(60000,784)
X_test=X_test.reshape(10000,784)
X_train=X_train.astype('float32')
X_test=X_test.astype('float32')

In [8]:
#normalising the data to help with the training
X_train=X_train/255 #we can write like this as well X_train /=255
X_test=X_test/255 #we can write like this as well X_test /=255

In [9]:
#one hot encoding using keras numpy related utilities
n_classes=10
print("Shape before one hot encoding: ", y_train.shape)
y_train=to_categorical(y_train,n_classes)
y_test=to_categorical(y_test,n_classes)
print("Shape after one hot encoding: ", y_train.shape)

Shape before one hot encoding:  (60000,)
Shape after one hot encoding:  (60000, 10)


In [10]:
#building a linear stock with sequential model
model=Sequential()

In [11]:
#hidden layer
model.add(Dense(100,input_shape=(784,), activation='relu'))

C:\python 3.11\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [12]:
#output layer
model.add(Dense(10, activation='softmax'))

In [13]:
#looking the model summary
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 100)                 │          78,500 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 10)                  │           1,010 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 79,510 (310.59 KB)

 Trainable params: 79,510 (310.59 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
#compiling the sequential model
model.compile(loss='categorical_crossentropy',
              metrics=['accuracy'], optimizer='adam')

In [15]:
#training the model for 10 epochs
model.fit(X_train,y_train, batch_size=128, epochs=10,
         validation_data=(X_test, y_test))

Epoch 1/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.8207 - loss: 0.6505 - val_accuracy: 0.9421 - val_loss: 0.2021
Epoch 2/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.9472 - loss: 0.1826 - val_accuracy: 0.9575 - val_loss: 0.1465
Epoch 3/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.9626 - loss: 0.1339 - val_accuracy: 0.9625 - val_loss: 0.1196
Epoch 4/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.9714 - loss: 0.1040 - val_accuracy: 0.9684 - val_loss: 0.1034
Epoch 5/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.9769 - loss: 0.0827 - val_accuracy: 0.9680 - val_loss: 0.1040
Epoch 6/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.9803 - loss: 0.0705 - val_accuracy: 0.9737 - val_loss: 0.0863
Epoch 7/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.9826 - loss: 0.0602 - val_accuracy: 0.9746 - val_loss: 0.0809
Epoch 8/10
469/469 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.9857 - loss: 0.0512 - val_accuracy: 0.